In [1]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

## 1.  Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## 2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

for i in list_:
    print('datatype of each element of list_',type(i),'and the element is ',i)
    
for i in array_list:
    print('datatype of each element of array_list is ',type(i),'and the element is',i)

datatype of each element of list_ <class 'str'> and the element is  1
datatype of each element of list_ <class 'str'> and the element is  2
datatype of each element of list_ <class 'str'> and the element is  3
datatype of each element of list_ <class 'str'> and the element is  4
datatype of each element of list_ <class 'str'> and the element is  5
datatype of each element of array_list is  <class 'numpy.str_'> and the element is 1
datatype of each element of array_list is  <class 'numpy.str_'> and the element is 2
datatype of each element of array_list is  <class 'numpy.str_'> and the element is 3
datatype of each element of array_list is  <class 'numpy.str_'> and the element is 4
datatype of each element of array_list is  <class 'numpy.str_'> and the element is 5


## 3(a). Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [5]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

for i in array_list:
    print('datatype of each element of array_list is ',type(i),'the element is ',i)

datatype of each element of array_list is  <class 'numpy.int64'> the element is  1
datatype of each element of array_list is  <class 'numpy.int64'> the element is  2
datatype of each element of array_list is  <class 'numpy.int64'> the element is  3
datatype of each element of array_list is  <class 'numpy.int64'> the element is  4
datatype of each element of array_list is  <class 'numpy.int64'> the element is  5


## 3(b).

In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

for i in num_array:
    print('datatype of each element of num_array is ',type(i),'the array is', i)

datatype of each element of num_array is  <class 'numpy.ndarray'> the array is [1 2 3]
datatype of each element of num_array is  <class 'numpy.ndarray'> the array is [4 5 6]


## 4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

  **shape** attribute is used to get the dimensions of a NumPy array.

In [1]:
## shape attribute is used to get the dimensions of a NumPy array
import numpy as np
a = np.random.random(50).reshape(5,2,5)
print(a.shape)

(5, 2, 5)


 **size** attribute is used to get the total number of elements in a NumPy array. It returns the total number of elements in the array as an integer value.

In [2]:
import numpy as np
a = np.random.random(50).reshape(5,2,5)
print(a.size)

50


## 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [5]:
zeros_3 = np.zeros((3,3),dtype="int")
print(zeros_3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 6. Create an identity matrix of shape (5,5) using numpy functions?

In [6]:
id_matrix = np.identity(5,dtype='int')
print(id_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
